from enum import Enum

class WorldRegion(str, Enum):
    ALASKA = "Alaska"
    NORTHWEST_TERRITORY = "Northwest Territory"
    ALBERTA = "Alberta"
    ONTARIO = "Ontario"
    EASTERN_CANADA = "Eastern Canada"
    WESTERN_US = "Western United States"
    EASTERN_US = "Eastern United States"
    GREENLAND = "Greenland"
    VENEZUELA = "Venezuela"
    PERU = "Peru"
    BRAZIL = "Brazil"
    ARGENTINA = "Argentina"
    ICELAND = "Iceland"
    SCANDINAVIA = "Scandinavia"
    NORTHERN_EUROPE = "Northern Europe"
    WESTERN_EUROPE = "Western Europe"
    SOUTHERN_EUROPE = "Southern Europe"
    RUSSIA = "Russia"
    URAL = "Ural"
    SIBERIA = "Siberia"
    YAKUTSK = "Yakutsk"
    KAMCHATKA = "Kamchatka"
    MONGOLIA = "Mongolia"
    IRKUTSK = "Irkutsk"
    CHINA = "China"
    INDIA = "India"
    AFGHANISTAN = "Afghanistan"
    MIDDLE_EAST = "Middle East"
    SOUTHEAST_ASIA = "Southeast Asia"
    INDONESIA = "Indonesia"
    NEW_GUINEA = "New Guinea"
    WESTERN_AUSTRALIA = "Western Australia"
    EASTERN_AUSTRALIA = "Eastern Australia"
    EGYPT = "Egypt"
    NORTH_AFRICA = "North Africa"
    CENTRAL_AFRICA = "Central Africa"
    EAST_AFRICA = "East Africa"
    SOUTH_AFRICA = "South Africa"

class WorldRegionTR(str, Enum):
    ALASKA = "Alaska"
    NORTHWEST_TERRITORY = "Kuzeybatı Toprakları"      # Northwest Territory
    ALBERTA = "Alberta"
    ONTARIO = "Ontario"
    EASTERN_CANADA = "Doğu Kanada"                  # Eastern Canada
    WESTERN_US = "Batı Amerika Birleşik Devletleri"  # Western United States
    EASTERN_US = "Doğu Amerika Birleşik Devletleri"  # Eastern United States
    GREENLAND = "Grönland"                          # Greenland
    VENEZUELA = "Venezuela"
    PERU = "Peru"
    BRAZIL = "Brezilya"                             # Brazil
    ARGENTINA = "Arjantin"                          # Argentina
    ICELAND = "İzlanda"                             # Iceland
    SCANDINAVIA = "İskandinavya"                    # Scandinavia
    NORTHERN_EUROPE = "Kuzey Avrupa"                # Northern Europe
    WESTERN_EUROPE = "Batı Avrupa"                  # Western Europe
    SOUTHERN_EUROPE = "Güney Avrupa"                # Southern Europe
    RUSSIA = "Rusya"                                # Russia
    URAL = "Ural"
    SIBERIA = "Sibirya"                             # Siberia
    YAKUTSK = "Yakutistan"                          # Yakutsk
    KAMCHATKA = "Kamçatka"                          # Kamchatka
    MONGOLIA = "Moğolistan"                         # Mongolia
    IRKUTSK = "İrkutsk"                             # Irkutsk
    CHINA = "Çin"                                   # China
    INDIA = "Hindistan"                             # India
    AFGHANISTAN = "Afganistan"                      # Afghanistan
    MIDDLE_EAST = "Orta Doğu"                       # Middle East
    SOUTHEAST_ASIA = "Güneydoğu Asya"                # Southeast Asia
    INDONESIA = "Endonezya"                         # Indonesia
    NEW_GUINEA = "Yeni Gine"                        # New Guinea
    WESTERN_AUSTRALIA = "Batı Avustralya"             # Western Australia
    EASTERN_AUSTRALIA = "Doğu Avustralya"             # Eastern Australia
    EGYPT = "Mısır"                                 # Egypt
    NORTH_AFRICA = "Kuzey Afrika"                   # North Africa
    CENTRAL_AFRICA = "Orta Afrika"                  # Central Africa
    EAST_AFRICA = "Doğu Afrika"                     # East Africa
    SOUTH_AFRICA = "Güney Afrika"                   # South Africa